[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
startCommand = "node gemini-server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"